import type { Movie } from "./types";

/**
 * Curated demo dataset. Swap `src/lib/movies/api.ts` for your Neo4j-backed
 * client and this file can disappear entirely.
 */
export const MOVIES: Movie[] = [
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    rating: 8.8,
    runtime: 148,
    genres: ["Sci-Fi", "Thriller", "Action"],
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Cillian Murphy"],
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task: plant an idea into the mind of a C.E.O.",
    hue: 28,
    popularity: 98,
    trending: true,
  },
  {
    id: "interstellar",
    title: "Interstellar",
    year: 2014,
    rating: 8.7,
    runtime: 169,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    description:
      "With Earth's future in doubt, a team of explorers travels through a wormhole in search of a new home for humanity.",
    hue: 210,
    popularity: 96,
    trending: true,
  },
  {
    id: "tenet",
    title: "Tenet",
    year: 2020,
    rating: 7.3,
    runtime: 150,
    genres: ["Sci-Fi", "Action", "Thriller"],
    director: "Christopher Nolan",
    cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki", "Kenneth Branagh"],
    description:
      "Armed with a single word, a protagonist journeys through a twilight world of international espionage where time runs both ways.",
    hue: 195,
    popularity: 80,
  },
  {
    id: "the-dark-knight",
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    runtime: 152,
    genres: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"],
    description:
      "Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy and forces the Dark Knight to confront his limits.",
    hue: 250,
    popularity: 99,
    trending: true,
  },
  {
    id: "the-prestige",
    title: "The Prestige",
    year: 2006,
    rating: 8.5,
    runtime: 130,
    genres: ["Drama", "Mystery", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine"],
    description:
      "Two rival stage magicians in Victorian London engage in a bitter battle of one-upmanship with tragic consequences.",
    hue: 40,
    popularity: 78,
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    year: 2023,
    rating: 8.4,
    runtime: 180,
    genres: ["Drama", "History", "Thriller"],
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr.", "Matt Damon", "Florence Pugh"],
    description:
      "The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    hue: 18,
    popularity: 94,
    trending: true,
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    rating: 8.0,
    runtime: 164,
    genres: ["Sci-Fi", "Drama", "Mystery"],
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Jared Leto"],
    description:
      "A young blade runner uncovers a long-buried secret that could plunge what's left of society into chaos.",
    hue: 330,
    popularity: 88,
    trending: true,
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    rating: 7.9,
    runtime: 116,
    genres: ["Sci-Fi", "Drama", "Mystery"],
    director: "Denis Villeneuve",
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    description:
      "A linguist is recruited to communicate with alien visitors and discovers a truth that reshapes her understanding of time.",
    hue: 160,
    popularity: 82,
  },
  {
    id: "dune",
    title: "Dune",
    year: 2021,
    rating: 8.0,
    runtime: 155,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya", "Josh Brolin"],
    description:
      "Paul Atreides travels to the most dangerous planet in the universe to secure the future of his family and his people.",
    hue: 36,
    popularity: 93,
    trending: true,
  },
  {
    id: "sicario",
    title: "Sicario",
    year: 2015,
    rating: 7.6,
    runtime: 121,
    genres: ["Crime", "Thriller", "Action"],
    director: "Denis Villeneuve",
    cast: ["Emily Blunt", "Benicio del Toro", "Josh Brolin"],
    description:
      "An idealistic FBI agent is enlisted by a government task force to escalate the war against drugs at the border.",
    hue: 20,
    popularity: 74,
  },
  {
    id: "the-departed",
    title: "The Departed",
    year: 2006,
    rating: 8.5,
    runtime: 151,
    genres: ["Crime", "Drama", "Thriller"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"],
    description:
      "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.",
    hue: 8,
    popularity: 85,
  },
  {
    id: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    rating: 8.2,
    runtime: 138,
    genres: ["Mystery", "Thriller", "Drama"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley", "Michelle Williams"],
    description:
      "A U.S. Marshal investigates the disappearance of a patient from a hospital for the criminally insane.",
    hue: 205,
    popularity: 79,
  },
  {
    id: "the-wolf-of-wall-street",
    title: "The Wolf of Wall Street",
    year: 2013,
    rating: 8.2,
    runtime: 180,
    genres: ["Comedy", "Crime", "Drama"],
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"],
    description:
      "The rise and spectacular fall of stockbroker Jordan Belfort, told at full, unrepentant volume.",
    hue: 48,
    popularity: 87,
  },
  {
    id: "goodfellas",
    title: "Goodfellas",
    year: 1990,
    rating: 8.7,
    runtime: 145,
    genres: ["Crime", "Drama"],
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    description:
      "Henry Hill's three decades inside the mob, from wide-eyed apprentice to paranoid informant.",
    hue: 12,
    popularity: 84,
  },
  {
    id: "pulp-fiction",
    title: "Pulp Fiction",
    year: 1994,
    rating: 8.9,
    runtime: 154,
    genres: ["Crime", "Drama", "Thriller"],
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
    description:
      "The lives of two hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    hue: 355,
    popularity: 92,
  },
  {
    id: "django-unchained",
    title: "Django Unchained",
    year: 2012,
    rating: 8.4,
    runtime: 165,
    genres: ["Western", "Drama", "Action"],
    director: "Quentin Tarantino",
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Samuel L. Jackson"],
    description:
      "A freed slave and a German bounty hunter set out to rescue his wife from a brutal Mississippi plantation owner.",
    hue: 26,
    popularity: 83,
  },
  {
    id: "inglourious-basterds",
    title: "Inglourious Basterds",
    year: 2009,
    rating: 8.3,
    runtime: 153,
    genres: ["Drama", "War", "Adventure"],
    director: "Quentin Tarantino",
    cast: ["Brad Pitt", "Christoph Waltz", "Michael Fassbender", "Mélanie Laurent"],
    description:
      "In Nazi-occupied France, a plan to assassinate Nazi leaders converges with a cinema owner's private revenge.",
    hue: 0,
    popularity: 81,
  },
  {
    id: "parasite",
    title: "Parasite",
    year: 2019,
    rating: 8.5,
    runtime: 132,
    genres: ["Thriller", "Drama", "Comedy"],
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between two very different families.",
    hue: 100,
    popularity: 91,
    trending: true,
  },
  {
    id: "snowpiercer",
    title: "Snowpiercer",
    year: 2013,
    rating: 7.1,
    runtime: 126,
    genres: ["Sci-Fi", "Action", "Drama"],
    director: "Bong Joon-ho",
    cast: ["Chris Evans", "Tilda Swinton", "Song Kang-ho", "Jamie Bell"],
    description:
      "In a frozen future, the last of humanity rides an endlessly circling train where class war moves car by car.",
    hue: 190,
    popularity: 70,
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    rating: 8.1,
    runtime: 120,
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    description:
      "In a post-apocalyptic wasteland, a drifter and a rebel commander flee a tyrant across a burning desert.",
    hue: 22,
    popularity: 86,
  },
  {
    id: "the-social-network",
    title: "The Social Network",
    year: 2010,
    rating: 7.8,
    runtime: 120,
    genres: ["Drama", "History"],
    director: "David Fincher",
    cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer"],
    description:
      "The founding of a social network and the lawsuits, betrayals and ambition that came with it.",
    hue: 200,
    popularity: 73,
  },
  {
    id: "fight-club",
    title: "Fight Club",
    year: 1999,
    rating: 8.8,
    runtime: 139,
    genres: ["Drama", "Thriller"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    description:
      "An insomniac office worker and a soap salesman form an underground club that spirals far beyond their control.",
    hue: 15,
    popularity: 89,
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    year: 2014,
    rating: 8.1,
    runtime: 149,
    genres: ["Mystery", "Thriller", "Drama"],
    director: "David Fincher",
    cast: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
    description:
      "A man becomes the prime suspect in the disappearance of his wife, and the media circus does the rest.",
    hue: 215,
    popularity: 77,
  },
  {
    id: "se7en",
    title: "Se7en",
    year: 1995,
    rating: 8.6,
    runtime: 127,
    genres: ["Crime", "Mystery", "Thriller"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Morgan Freeman", "Kevin Spacey", "Gwyneth Paltrow"],
    description:
      "Two detectives hunt a serial killer who uses the seven deadly sins as the blueprint for his murders.",
    hue: 120,
    popularity: 80,
  },
  {
    id: "the-matrix",
    title: "The Matrix",
    year: 1999,
    rating: 8.7,
    runtime: 136,
    genres: ["Sci-Fi", "Action"],
    director: "Lana Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    description:
      "A hacker discovers that reality is a simulation and joins a rebellion against the machines that built it.",
    hue: 140,
    popularity: 95,
    trending: true,
  },
  {
    id: "whiplash",
    title: "Whiplash",
    year: 2014,
    rating: 8.5,
    runtime: 106,
    genres: ["Drama", "Music"],
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    description:
      "A young drummer is pushed to the edge of his limits by an instructor who accepts nothing short of greatness.",
    hue: 45,
    popularity: 82,
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    rating: 8.0,
    runtime: 128,
    genres: ["Drama", "Music", "Romance"],
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    description:
      "A jazz pianist and an aspiring actress fall in love while chasing their dreams through Los Angeles.",
    hue: 280,
    popularity: 84,
  },
  {
    id: "drive",
    title: "Drive",
    year: 2011,
    rating: 7.8,
    runtime: 100,
    genres: ["Crime", "Drama", "Thriller"],
    director: "Nicolas Winding Refn",
    cast: ["Ryan Gosling", "Carey Mulligan", "Bryan Cranston", "Oscar Isaac"],
    description:
      "A Hollywood stunt driver moonlighting as a getaway wheelman gets caught between a heist and the mob.",
    hue: 310,
    popularity: 76,
  },
  {
    id: "her",
    title: "Her",
    year: 2013,
    rating: 8.0,
    runtime: 126,
    genres: ["Sci-Fi", "Drama", "Romance"],
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"],
    description:
      "A lonely writer falls in love with an operating system designed to meet his every need.",
    hue: 8,
    popularity: 75,
  },
  {
    id: "no-country-for-old-men",
    title: "No Country for Old Men",
    year: 2007,
    rating: 8.2,
    runtime: 122,
    genres: ["Crime", "Thriller", "Western"],
    director: "Joel Coen",
    cast: ["Josh Brolin", "Javier Bardem", "Tommy Lee Jones", "Woody Harrelson"],
    description:
      "A hunter stumbles onto a drug deal gone wrong and a relentless killer follows the money to the end.",
    hue: 32,
    popularity: 78,
  },
];

export const ALL_GENRES = Array.from(new Set(MOVIES.flatMap((m) => m.genres))).sort();

export const ALL_DECADES = Array.from(
  new Set(MOVIES.map((m) => `${Math.floor(m.year / 10) * 10}s`)),
).sort();
