/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as MoviesIdRouteImport } from './routes/movies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/movies/$id': typeof MoviesIdRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/movies/$id'
    | '/movies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/movies/$id'
    | '/movies'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/login'
    | '/recommendations'
    | '/register'
    | '/search'
    | '/movies/$id'
    | '/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  MoviesIdRoute: typeof MoviesIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  MoviesIdRoute: MoviesIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
